### ISSUE TITLE
SDK itself

### ISSUE THREAD

**Issue by kazurov** [KIT-IAI/SDM_Plugin_General#2]
Hi! Where can I find SDK used for plugins described here?

**Comment by arch1501** [comment]
Hello, 
The required libs are included in the HelloWorld Plugin, for example.
We are currently preparing an update to version 7.3. Various changes have been made also to the plugin interface. If you are interested, please send me a private message and we will prepare a complete archive with the current status of the libs.
Kind regards
Andreas
